# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: eyal-lezmy
description: "Personal page for Eyal Lezmy"
keywords: "Android, Genymotion, Genymobile, Paris Android User Group, PAUG, mobile, Paris, France, web, development, dev, Java, GDE, Droidcon"
url: http://eyal.fr
baseurl: ""
# baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/eyal-lezmy/eyal.fr
disqus_shortname: "eyal-lezmy"

# Author settings
author:
  name      : Eyal Lezmy
  job       : Software Engineer
  bio       : ""
  thumb     : /images/author.jpg
  email     : 
  url       : http://eyal.fr
  github    : http://github.com/eyal-lezmy
  twitter   : http://twitter.com/Eyal_Lezmy
  linkedin  : https://www.linkedin.com/in/eyallezmy
  google-plus  : https://plus.google.com/+EyalLEZMY

# navbar pages
navbar:
  #- slug: about
  #  title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  #- slug: blog
  #  title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
